site_name: Firebreak
site_url: https://example.com/

plugins: [] disables all plugins

nav:
    - Home: index.md

theme:
    name: gds
    show_govuk_logo: false

    show_cookie_banner: false
    show_phase_banner: false

    sticky_header_desktop: true
    sticky_side_nav_desktop: true

