site_name: Theme Dev
site_url: https://example.com/

#plugins: [] disables all plugins

nav:
    - Home: index.md
    - About: about.md

theme:
    name: mkdocs
    custom_dir: ../../src/
    show_govuk_logo: false

    show_cookie_banner: false

    show_phase_banner: false
    phase: beta
    feedback_url: https://www.gov.uk/government/organisations/department-for-international-trade

    sticky_header_desktop: true
    sticky_side_nav_desktop: true

