site_name: GDS Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - Lorem: about.md
    - Markdown: markdown-cheat-sheet.md
    - Child Test:
        - Child: child-of-markdown.md

theme:
    name: mkdocs
    custom_dir: gds/
#    show_govuk_logo: true

    show_cookie_banner: false

    show_phase_banner: false
    phase: beta
    feedback_url: https://www.gov.uk/government/organisations/department-for-international-trade

#    sticky_header_desktop: true
    sticky_side_nav_desktop: true

